# for loading and saving paths
[path]
data_type = "DNS-Challenge_3000h"
is_checkpoint = true
is_resume_reload = false
checkpoint_load_path = "CheckpointPath"
checkpoint_load_filename = ""
loss_save_path = "Loss"
model_best_path = "BestModel"
logging_path = "Logger"


[path.train]
mix_file_path = "/media/liandong/CTS_TASLP_for_dns_3000h_dataset/train/mix"
target_file_path = "/media/liandong/CTS_TASLP_for_dns_3000h_dataset/train/clean"

[path.val]
mix_file_path = "/media/liandong/CTS_TASLP_for_dns_3000h_dataset/dev/mix"
target_file_path = "/media/liandong/CTS_TASLP_for_dns_3000h_dataset/dev/clean"


[gpu]
gpu_ids = [1]
# signal settings before sending into the network
[signal]
sr = 16000
is_chunk = true
chunk_length = 8.0
win_size = 0.02
win_shift = 0.01
fft_num = 320
is_variance_norm = true
is_compress = true


# choosed loss function
[loss_function]
path = "utils.loss"
prev_weight = 0.1
curr_weight = 1.0
alpha = 0.5
l_type = "L2"
[loss_function.stagewise]
classname = "StagewiseComMagEuclideanLoss"


# choosed optimizer
[optimizer]
name = "adam"
lr = 2e-4
beta1 = 0.9
beta2 = 0.999
l2 = 1e-7
gradient_norm = 5.0
epochs = 60
halve_lr = true
early_stop = true
halve_freq = 2
early_stop_freq = 3
print_freq = 200
metric_options = ["SISNR"]  # only one metric is supported in the current version, chioces: [NB-PESQ, ESTOI]

# reproducibility settings
[reproducibility]
seed = 1234

# Dataset
[dataset]
[dataset.train]
json_path = "/media/liandong/CTS_TASLP_for_dns_3000h_dataset/Json/train"
batch_size = 24
is_shuffle = true

[dataset.val]
json_path = "/media/liandong/CTS_TASLP_for_dns_3000h_dataset/Json/dev"
batch_size = 24
is_shuffle = true

[dataloader]
[dataloader.train]
num_workers = 6
pin_memory = true
drop_last = false
shuffle = false

[dataloader.val]
num_workers = 6
pin_memory = true
drop_last = false
shuffle = false

# network configs
[net]
choice="G2Net"
path = "nets.g2Net"
classname = "G2Net"

[net.G2Net.args]
k1 = [2,3]
k2 = [1,3]
c = 64
intra_connect = "cat"
d_feat = 256
kd1 = 3
cd1 = 64
tcn_num = 2
dilas = [1,2,5,9]
fft_num = 320
is_causal = true
acti_type = "sigmoid"
crm_type = "crm1"
stage_num = 3
u_type = "u2"
head_type = "RI+MAG"
norm_type = "IN"


[save]
loss_filename = "DNS-Challenge_3000h_g2net_IN_causal_loss.mat"
best_model_filename = "DNS-Challenge_3000h_g2net_IN_causal_model.pth"
checkpoint_filename = "DNS-Challenge_3000h_g2net_IN_causal_model.pth.tar"
logger_filename = "DNS-Challenge_3000h_gagnet_IN_causal.txt"
#tensorboard_filename = "librispeech_taylorbeamformer_mic_linear_mid_target_timvdr_order0_param_nonshared_bf_embedding64_hidnode_64_u2_risqueezed_norm2d_BN_norm1d_BN_causal"

